openapi: 3.1.0
info:
  version: 1.0.0
  title: Toggl
  description: ''
  contact:
    name: xxx
    url: xxx
    email: xxx@xxx.com
servers:
  - url: 'https://api.track.toggl.com/api/v8'
paths:
  /time_entries:
    post:
      tags:
        - time_entries
      description: ''
      operationId: createTimeEntry
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    data:
                      id: 436694100
                      pid: 123
                      wid: 777
                      billable: false
                      start: '2013-03-05T07:58:58.000Z'
                      duration: 1200
                      description: Meeting with possible clients
                      tags:
                        - billed
                properties:
                  data:
                    $ref: '#/components/schemas/TimeEntry'
                required:
                  - data
              examples:
                example-1:
                  value:
                    data:
                      id: 436694100
                      pid: 123
                      wid: 777
                      billable: false
                      start: '2013-03-05T07:58:58.000Z'
                      duration: 1200
                      description: Meeting with possible clients
                      tags:
                        - billed
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  time_entry:
                    description: Meeting with possible clients
                    tags:
                      - billed
                    duration: 1200
                    start: '2013-03-05T07:58:58.000Z'
                    pid: 123
                    created_with: curl
              properties:
                time_entry:
                  $ref: '#/components/schemas/CreateTimeEntryRequest'
              required:
                - time_entry
            examples:
              example-1:
                value:
                  time_entry:
                    description: Meeting with possible clients
                    tags:
                      - billed
                    duration: 1200
                    start: '2013-03-05T07:58:58.000Z'
                    pid: 123
                    created_with: curl
      security:
        - UserAuhtnetication: []
  /time_entries/start:
    post:
      description: ''
      tags:
        - time_entries
      summary: ''
      operationId: startTimeEntry
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    data:
                      id: 436694100
                      pid: 123
                      wid: 777
                      billable: false
                      start: '2013-03-05T07:58:58.000Z'
                      duration: -1362470338
                      description: Meeting with possible clients
                      tags:
                        - billed
                properties:
                  data:
                    $ref: '#/components/schemas/TimeEntry'
                required:
                  - data
              examples:
                example-1:
                  value:
                    data:
                      id: 436694100
                      pid: 123
                      wid: 777
                      billable: false
                      start: '2013-03-05T07:58:58.000Z'
                      duration: -1362470338
                      description: Meeting with possible clients
                      tags:
                        - billed
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  time_entry:
                    description: Meeting with possible clients
                    tags:
                      - billed
                    pid: 123
                    created_with: curl
              properties:
                time_entry:
                  $ref: '#/components/schemas/StartTimeEntryRequest'
              required:
                - time_entry
            examples:
              example-1:
                value:
                  time_entry:
                    description: Meeting with possible clients
                    tags:
                      - billed
                    pid: 123
                    created_with: curl
      security:
        - UserAuhtnetication: []
  '/time_entries/{time_entry_id}/stop':
    parameters:
      - schema:
          type: integer
        name: time_entry_id
        in: path
        required: true
    put:
      description: ''
      tags:
        - time_entries
      summary: ''
      operationId: stopTimeEntry
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    data:
                      id: 436694100
                      pid: 123
                      wid: 777
                      billable: false
                      start: '2013-03-05T07:58:58.000Z'
                      duration: 60
                      description: Meeting with possible clients
                      tags:
                        - billed
                properties:
                  data:
                    $ref: '#/components/schemas/TimeEntry'
                required:
                  - data
              examples:
                succeed:
                  value:
                    data:
                      id: 436694100
                      pid: 123
                      wid: 777
                      billable: false
                      start: '2013-03-05T07:58:58.000Z'
                      duration: 60
                      description: Meeting with possible clients
                      tags:
                        - billed
      security:
        - UserAuhtnetication: []
  '/time_entries/{time_entry_id}':
    parameters:
      - schema:
          type: integer
        name: time_entry_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/TimeEntry'
              examples:
                succeed:
                  value:
                    data:
                      id: 436694100
                      pid: 123
                      wid: 777
                      billable: false
                      start: '2013-03-05T07:58:58.000Z'
                      duration: 60
                      description: Meeting with possible clients
                      tags:
                        - billed
      operationId: getTimeEntry
      security:
        - UserAuhtnetication: []
    put:
      tags:
        - time_entries
      summary: ''
      operationId: putTimeEntry
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/TimeEntry'
                required:
                  - data
                x-examples:
                  example-1:
                    data:
                      id: 436694100
                      pid: 123
                      wid: 777
                      billable: true
                      start: '2013-03-05T07:58:58.000Z'
                      stop: '2013-03-05T08:58:58.000Z'
                      duration: 1240
                      description: Meeting with possible clients
                      at: '2013-03-05T12:34:50+00:00'
              examples:
                succeed:
                  value:
                    data:
                      id: 436694100
                      pid: 123
                      wid: 777
                      billable: true
                      start: '2013-03-05T07:58:58.000Z'
                      stop: '2013-03-05T08:58:58.000Z'
                      duration: 1240
                      description: Meeting with possible clients
                      at: '2013-03-05T12:34:50+00:00'
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  time_entry:
                    description: Meeting with possible clients
                    tags:
                      - ''
                    duration: 1240
                    start: '2013-03-05T07:58:58.000Z'
                    stop: '2013-03-05T08:58:58.000Z'
                    duronly: true
                    pid: 123
                    billable: true
              properties:
                time_entry:
                  type: object
                  required:
                    - description
                    - tags
                    - duration
                    - start
                    - stop
                    - duronly
                    - pid
                    - billable
                  properties:
                    description:
                      type: string
                      minLength: 1
                    tags:
                      type: array
                      items:
                        type: string
                    duration:
                      type: integer
                    start:
                      type: string
                      minLength: 1
                    stop:
                      type: string
                      minLength: 1
                    duronly:
                      type: boolean
                    pid:
                      type: integer
                    billable:
                      type: boolean
              required:
                - time_entry
            examples:
              succeed:
                value:
                  time_entry:
                    description: Meeting with possible clients
                    tags:
                      - ''
                    duration: 1240
                    start: '2013-03-05T07:58:58.000Z'
                    stop: '2013-03-05T08:58:58.000Z'
                    duronly: true
                    pid: 123
                    billable: true
  /time_entries/current:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    data:
                      id: 436694100
                      wid: 777
                      pid: 193791
                      billable: false
                      start: '2014-01-30T09:08:04+00:00'
                      duration: -1391072884
                      description: Running time entry
                      at: '2014-01-30T09:08:12+00:00'
                properties:
                  data:
                    $ref: '#/components/schemas/TimeEntry'
                required:
                  - data
              examples:
                succeed:
                  value:
                    data:
                      id: 436694100
                      wid: 777
                      pid: 193791
                      billable: false
                      start: '2014-01-30T09:08:04+00:00'
                      duration: -1391072884
                      description: Running time entry
                      at: '2014-01-30T09:08:12+00:00'
      operationId: getCurrentTimeEntry
      security:
        - UserAuhtnetication: []
  /workspaces:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - id
                    - name
                    - premium
                    - admin
                    - default_hourly_rate
                    - default_currency
                    - only_admins_may_create_projects
                    - only_admins_see_billable_rates
                    - rounding
                    - rounding_minutes
                    - at
                  properties:
                    id:
                      type: number
                    name:
                      type: string
                      minLength: 1
                    premium:
                      type: boolean
                    admin:
                      type: boolean
                    default_hourly_rate:
                      type: number
                    default_currency:
                      type: string
                      minLength: 1
                    only_admins_may_create_projects:
                      type: boolean
                    only_admins_see_billable_rates:
                      type: boolean
                    rounding:
                      type: number
                    rounding_minutes:
                      type: number
                    at:
                      type: string
                      minLength: 1
                    logo_url:
                      type: string
                      minLength: 1
                x-examples:
                  example-1:
                    - id: 3134975
                      name: John's personal ws
                      premium: true
                      admin: true
                      default_hourly_rate: 50
                      default_currency: USD
                      only_admins_may_create_projects: false
                      only_admins_see_billable_rates: true
                      rounding: 1
                      rounding_minutes: 15
                      at: '2013-08-28T16:22:21+00:00'
                      logo_url: my_logo.png
                    - id: 777
                      name: My Company Inc
                      premium: true
                      admin: true
                      default_hourly_rate: 40
                      default_currency: EUR
                      only_admins_may_create_projects: false
                      only_admins_see_billable_rates: true
                      rounding: 1
                      rounding_minutes: 15
                      at: '2013-08-28T16:22:21+00:00'
              examples:
                succeed:
                  value:
                    - id: 3134975
                      name: John's personal ws
                      premium: true
                      admin: true
                      default_hourly_rate: 50
                      default_currency: USD
                      only_admins_may_create_projects: false
                      only_admins_see_billable_rates: true
                      rounding: 1
                      rounding_minutes: 15
                      at: '2013-08-28T16:22:21+00:00'
                      logo_url: my_logo.png
                    - id: 777
                      name: My Company Inc
                      premium: true
                      admin: true
                      default_hourly_rate: 40
                      default_currency: EUR
                      only_admins_may_create_projects: false
                      only_admins_see_billable_rates: true
                      rounding: 1
                      rounding_minutes: 15
                      at: '2013-08-28T16:22:21+00:00'
      operationId: getWorkspaces
  '/workspaces/{workspace_id}/projects':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                x-examples:
                  example-1:
                    - id: 909
                      wid: 777
                      cid: 987
                      name: Very lucrative project
                      billable: false
                      is_private: true
                      active: true
                      at: '2013-03-06T09:15:18+00:00'
                    - id: 32123
                      wid: 777
                      cid: 123
                      name: Factory server infrastructure
                      billable: true
                      is_private: true
                      active: true
                      at: '2013-03-06T09:16:06+00:00'
                items:
                  $ref: '#/components/schemas/Project'
              examples:
                succeed:
                  value:
                    - id: 909
                      wid: 777
                      cid: 987
                      name: Very lucrative project
                      billable: false
                      is_private: true
                      active: true
                      at: '2013-03-06T09:15:18+00:00'
                    - id: 32123
                      wid: 777
                      cid: 123
                      name: Factory server infrastructure
                      billable: true
                      is_private: true
                      active: true
                      at: '2013-03-06T09:16:06+00:00'
      operationId: getProjects
    parameters:
      - schema:
          type: integer
        name: workspace_id
        in: path
        required: true
  '/workspaces/{workspace_id}/tags':
    parameters:
      - schema:
          type: integer
        name: workspace_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - id
                    - wid
                    - name
                  properties:
                    id:
                      type: number
                    wid:
                      type: number
                    name:
                      type: string
                      minLength: 1
                x-examples:
                  example-1:
                    - id: 151285
                      wid: 777
                      name: Billed
                    - id: 1596623
                      wid: 777
                      name: Invoiced
                    - id: 159643
                      wid: 777
                      name: Discarded
              examples:
                succeed:
                  value:
                    - id: 151285
                      wid: 777
                      name: Billed
                    - id: 1596623
                      wid: 777
                      name: Invoiced
                    - id: 159643
                      wid: 777
                      name: Discarded
      operationId: getTags
  '/projects/{project_id}':
    parameters:
      - schema:
          type: string
        name: project_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    data:
                      id: 193838628
                      wid: 777
                      cid: 123397
                      name: An awesome project
                      billable: false
                      is_private: true
                      active: true
                      at: '2013-03-06T12:15:37+00:00'
                      template: true
                      color: '5'
                properties:
                  data:
                    $ref: '#/components/schemas/Project'
                required:
                  - data
              examples:
                succeed:
                  value:
                    data:
                      id: 193838628
                      wid: 777
                      cid: 123397
                      name: An awesome project
                      billable: false
                      is_private: true
                      active: true
                      at: '2013-03-06T12:15:37+00:00'
                      template: true
                      color: '5'
      operationId: getProject
  '/projects':
    post:
      tags: []
      summary: ''
      operationId: createProject
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    data:
                      id: 193838628
                      wid: 777
                      cid: 123397
                      name: An awesome project
                      billable: false
                      is_private: true
                      active: true
                      at: '2013-03-06T12:15:37+00:00'
                      template_id: 10237
                      color: '5'
                properties:
                  data:
                    $ref: '#/components/schemas/Project'
                required:
                  - data
              examples:
                succeed:
                  value:
                    data:
                      id: 193838628
                      wid: 777
                      cid: 123397
                      name: An awesome project
                      billable: false
                      is_private: true
                      active: true
                      at: '2013-03-06T12:15:37+00:00'
                      template_id: 10237
                      color: '5'
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                project:
                  type: object
                  properties:
                    name:
                      type: string
                      minLength: 1
                    wid:
                      type: number
                    template_id:
                      type: number
                    is_private:
                      type: boolean
                    cid:
                      type: number
                  required:
                    - name
                    - wid
                    - template_id
                    - is_private
                    - cid
              required:
                - project
              x-examples:
                example-1:
                  project:
                    name: An awesome project
                    wid: 777
                    template_id: 10237
                    is_private: true
                    cid: 123397
            examples:
              example-1:
                value:
                  project:
                    name: An awesome project
                    wid: 777
                    template_id: 10237
                    is_private: true
                    cid: 123397
        description: ''
components:
  schemas:
    TimeEntry:
      description: ''
      type: object
      x-examples:
        example-1:
          id: 436694100
          pid: 123
          wid: 777
          billable: false
          start: '2013-03-05T07:58:58.000Z'
          duration: 60
          description: Meeting with possible clients
          tags:
            - billed
      examples:
        - id: 436694100
          pid: 123
          wid: 777
          billable: false
          start: '2013-03-05T07:58:58.000Z'
          duration: 60
          description: Meeting with possible clients
          tags:
            - billed
      properties:
        id:
          type: integer
        pid:
          type: integer
        wid:
          type: integer
        billable:
          type: boolean
        start:
          type: string
          minLength: 1
        duration:
          type: integer
        description:
          type: string
          minLength: 1
        tags:
          type: array
          items:
            type: string
        at:
          type: string
        duronly:
          type: boolean
      required:
        - id
        - pid
        - wid
        - billable
        - start
        - duration
    StartTimeEntryRequest:
      description: ''
      type: object
      x-examples:
        example-1:
          description: Meeting with possible clients
          tags:
            - billed
          pid: 123
          created_with: curl
      examples:
        - time_entry:
            description: Meeting with possible clients
            tags:
              - billed
            pid: 123
            created_with: curl
      properties:
        description:
          type: string
          minLength: 1
        tags:
          type: array
          items:
            type: string
        pid:
          type: integer
          minLength: 1
        created_with:
          type: string
          minLength: 1
      required:
        - description
        - tags
        - pid
        - created_with
    CreateTimeEntryRequest:
      description: ''
      type: object
      x-examples:
        example-1:
          description: Meeting with possible clients
          tags:
            - billed
          duration: 1200
          start: '2013-03-05T07:58:58.000Z'
          pid: 123
          created_with: curl
      examples:
        - time_entry:
            description: Meeting with possible clients
            tags:
              - billed
            duration: 1200
            start: '2013-03-05T07:58:58.000Z'
            pid: 123
            created_with: curl
      properties:
        description:
          type: string
          minLength: 1
        tags:
          type: array
          items:
            type: string
        duration:
          type: integer
        start:
          type: string
          minLength: 1
        pid:
          type: integer
        created_with:
          type: string
          minLength: 1
      required:
        - description
        - tags
        - duration
        - start
        - pid
        - created_with
    Project:
      description: ''
      type: object
      x-examples:
        example-1:
          id: 193838628
          wid: 777
          cid: 123397
          name: An awesome project
          billable: false
          is_private: true
          active: true
          at: '2013-03-06T12:15:37+00:00'
          template: true
          color: '5'
      examples:
        - id: 193838628
          wid: 777
          cid: 123397
          name: An awesome project
          billable: false
          is_private: true
          active: true
          at: '2013-03-06T12:15:37+00:00'
          template: true
          color: '5'
      properties:
        id:
          type: number
        wid:
          type: number
        cid:
          type: number
        name:
          type: string
          minLength: 1
        billable:
          type: boolean
        is_private:
          type: boolean
        active:
          type: boolean
        at:
          type: string
          minLength: 1
        template:
          type: boolean
        color:
          type: string
          minLength: 1
      required:
        - id
        - wid
        - cid
        - name
        - billable
        - is_private
        - active
        - at
  securitySchemes:
    UserAuhtnetication:
      type: http
      scheme: basic
security:
  - UserAuhtnetication: []
tags:
  - name: time_entries
